# Generated by Django 4.1.3 on 2023-01-21 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_team_leads_team_leads_remove_team_members_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Projects'},
        ),
    ]
